repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: [ "--unsafe" ]
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        entry: pyupgrade --py39-plus

  # pytest
  - repo: local
    hooks:
      #      - id: pytest-check
      #        name: pytest-check
      #        entry: pytest -s -v
      #        language: system
      #        types: [ python ]
      #        pass_filenames: false
      #        always_run: true

      - id: mypy
        name: mypy-local
        entry: mypy ondotori_client
        args: [ "--ignore-missing-imports" ]
        types: [ python ]
        language: system
        pass_filenames: false

      - id: format
        name: format-local
        entry: just format
        types: [ python ]
        language: system
        pass_filenames: false

      - id: lint
        name: lint-local
        entry: just lint
        types: [ python ]
        language: system
        pass_filenames: false
